# Generated by Django 6.0 on 2025-12-26 19:09

import django.core.validators
import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("cms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("photo", "Photo"),
                            ("medical_record", "Medical Record"),
                            ("id_document", "ID Document"),
                            ("insurance", "Insurance Document"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Allowed: PDF, JPG, PNG, GIF, DOC, DOCX, DCM (DICOM)",
                        upload_to=portal.models.upload_to_patient_folder,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "doc",
                                    "docx",
                                    "dcm",
                                ]
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Staff has verified this document"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("virus_scanned", models.BooleanField(default=False)),
                (
                    "virus_scan_result",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "visible_to_patient",
                    models.BooleanField(
                        default=True, help_text="Whether patient can see this file"
                    ),
                ),
                (
                    "shared_with_staff",
                    models.BooleanField(
                        default=True, help_text="Whether staff can access this file"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="booking.patient",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Upload",
                "verbose_name_plural": "Portal Uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("media_use", "Media Use (Photos/Videos)"),
                            ("testimonial", "Testimonial Publication"),
                            ("face_visible", "Face Visible in Media"),
                            ("before_after", "Before/After Photos"),
                            ("research", "Research Participation"),
                            ("marketing", "Marketing Communications"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=False, help_text="Whether consent is granted or denied"
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(
                        help_text="Full text of consent agreement shown to patient"
                    ),
                ),
                (
                    "patient_signature",
                    models.CharField(
                        blank=True,
                        help_text="Digital signature or typed name",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when consent was given",
                        null=True,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for consent",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When consent was revoked, if applicable",
                        null=True,
                    ),
                ),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="booking.patient",
                    ),
                ),
                (
                    "related_success_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to="cms.successstorypage",
                    ),
                ),
                (
                    "related_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to="portal.portalupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Record",
                "verbose_name_plural": "Consent Records",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("download", "Download"),
                            ("share", "Share"),
                            ("export", "Export"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource (e.g., 'Appointment', 'PortalUpload')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.IntegerField(
                        blank=True, help_text="ID of the resource", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the action",
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        default=False, help_text="Flagged by security monitoring"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Patient whose data was accessed or modified",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="booking.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="portal_audi_timesta_99e593_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="portal_audi_user_id_3c89c6_idx",
                    ),
                    models.Index(
                        fields=["patient", "-timestamp"],
                        name="portal_audi_patient_c34c5e_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="portal_audi_action_383992_idx",
                    ),
                ],
            },
        ),
    ]
