# Generated by Django 6.0 on 2026-01-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_add_patient_full_name"),
        ("portal", "0002_add_notification_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="related_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Appointment this consent is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_records",
                to="booking.appointment",
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who reviewed this consent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="staff_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes from staff review"
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("procedure_consent", "Surgery Procedure Consent"),
                    ("anesthesia_consent", "Anesthesia Consent"),
                    ("risks_acknowledgment", "Risks & Complications Acknowledgment"),
                    ("media_use", "Media Use (Photos/Videos)"),
                    ("testimonial", "Testimonial Publication"),
                    ("face_visible", "Face Visible in Media"),
                    ("before_after", "Before/After Photos"),
                    ("research", "Research Participation"),
                    ("marketing", "Marketing Communications"),
                    ("data_sharing", "Data Sharing with Partners"),
                ],
                max_length=50,
            ),
        ),
    ]
