# Generated by Django 6.0 on 2026-01-03 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_add_consent_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="revocation_requested_at",
            field=models.DateTimeField(
                blank=True, help_text="When patient requested revocation", null=True
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="revocation_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="revocation_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who reviewed the revocation request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revocation_reviewed_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("appointment_submitted", "Appointment Request Submitted"),
                    ("payment_verified", "Payment Verified"),
                    ("payment_rejected", "Payment Rejected"),
                    ("appointment_confirmed", "Appointment Confirmed"),
                    ("appointment_cancelled", "Appointment Cancelled"),
                    ("slot_assigned", "Time Slot Assigned"),
                    ("reminder", "Appointment Reminder"),
                    ("new_appointment", "New Appointment Request"),
                    ("payment_submitted", "Payment Proof Submitted"),
                    ("document_uploaded", "Document Uploaded"),
                    ("consent_granted", "Consent Granted"),
                    ("consent_revoked", "Consent Revoked"),
                ],
                max_length=50,
            ),
        ),
    ]
