# Generated by Django 6.0 on 2025-12-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "title",
                    models.CharField(help_text="e.g., MD, PhD, DPT", max_length=100),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("orthopedic-surgeon", "Orthopedic Surgeon"),
                            ("anesthesiologist", "Anesthesiologist"),
                            ("physical-therapist", "Physical Therapist"),
                            ("nurse", "Registered Nurse"),
                            ("patient-coordinator", "Patient Coordinator"),
                            ("nutritionist", "Nutritionist"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="e.g., Lead Surgeon, Physical Therapy Director",
                        max_length=100,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
                ("bio", models.TextField(help_text="Full biography")),
                (
                    "short_bio",
                    models.CharField(
                        help_text="Brief description for listings", max_length=300
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="Education and training, one per line"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Certifications and licenses, one per line",
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Languages spoken, comma-separated",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["order", "name"],
            },
        ),
    ]
