# Generated by Django 6.0 on 2026-01-09 18:46

import django.db.models.deletion
from django.db import migrations, models


def clear_photo_field(apps, schema_editor):
    """Clear existing photo paths before converting to ForeignKey."""
    Doctor = apps.get_model('core', 'Doctor')
    Doctor.objects.update(photo=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_site_settings"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order (lower = first)"
            ),
        ),
        # First, clear the photo field values (string paths can't convert to integer FKs)
        migrations.RunPython(clear_photo_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor's profile photo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.CreateModel(
            name="SupportTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient-coordinator", "Patient Coordinator"),
                            ("nurse", "Registered Nurse"),
                            ("physical-therapist", "Physical Therapist"),
                            ("nutritionist", "Nutritionist"),
                            ("admin", "Administrative Staff"),
                            ("translator", "Translator/Interpreter"),
                            ("driver", "Patient Transport"),
                            ("accommodation", "Accommodation Coordinator"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(help_text="Specific job title", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of their role and responsibilities"
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Languages spoken, comma-separated",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number if different",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team member's photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Team Member",
                "verbose_name_plural": "Support Team Members",
                "ordering": ["order", "name"],
            },
        ),
    ]
