# Generated by Django 6.0 on 2025-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="category",
            field=models.CharField(
                choices=[
                    ("nutrition", "Nutrition"),
                    ("recovery", "Recovery"),
                    ("procedures", "Procedures"),
                    ("patient-care", "Patient Care"),
                    ("research", "Research"),
                    ("news", "News"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
