# Generated by Django 6.0 on 2026-01-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_blogpage_category"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="after_image",
            field=models.ForeignKey(
                blank=True,
                help_text="After surgery image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="before_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Before surgery image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="doctor_description",
            field=models.TextField(
                blank=True,
                default="At Hills Clinic, our lead surgeon Dr. Khaqan Jahangir Janjua brings over 40 years of specialized experience in orthopedic and trauma surgery. With training from world-renowned institutions and hundreds of successful procedures, you're in expert hands.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="doctor_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main doctor photo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="doctor_name",
            field=models.CharField(
                default="Dr. Khaqan Jahangir Janjua", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="doctor_title",
            field=models.CharField(
                default="Pakistan's Premier Limb Lengthening Specialist", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat_countries",
            field=models.CharField(default="20+", max_length=50),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat_years",
            field=models.CharField(default="40+", max_length=50),
        ),
    ]
