# Generated by Django 6.0 on 2026-01-09 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_add_homepage_image_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_initials",
                    models.CharField(
                        help_text="Patient initials for privacy (e.g., 'J.S.')",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Patient's country (e.g., 'United States', 'UAE')",
                        max_length=100,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Patient's age at time of surgery",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("ilizarov", "Ilizarov Method"),
                            ("internal", "Internal Nail (PRECICE)"),
                            ("lon", "LON Method"),
                        ],
                        default="ilizarov",
                        max_length=50,
                    ),
                ),
                (
                    "height_gained",
                    models.CharField(
                        blank=True,
                        help_text="Height gained (e.g., '+3 inches', '+8cm')",
                        max_length=50,
                    ),
                ),
                (
                    "surgery_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year of surgery", null=True
                    ),
                ),
                (
                    "review_text",
                    models.TextField(help_text="The patient's review/testimonial text"),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Rating out of 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this review prominently"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Show this review on the website"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient Review",
                "verbose_name_plural": "Patient Reviews",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
