# Generated by Django 6.0 on 2025-12-26 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Karachi",
                        help_text="Patient's local timezone",
                        max_length=50,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ar", "Arabic"),
                            ("fa", "Persian"),
                            ("tr", "Turkish"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "current_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current height in centimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "desired_height_gain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Desired height gain in centimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Pre-existing medical conditions"
                    ),
                ),
                (
                    "medications",
                    models.TextField(blank=True, help_text="Current medications"),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known allergies"),
                ),
                (
                    "interested_in_procedure",
                    models.CharField(
                        choices=[
                            ("ilizarov", "Ilizarov (External)"),
                            ("internal", "Internal Nails"),
                            ("lon", "LON Method"),
                            ("undecided", "Not Sure Yet"),
                        ],
                        default="undecided",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Karachi",
                        help_text="Timezone for this slot (IANA timezone name)",
                        max_length=50,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Initial Consultation"),
                            ("follow_up", "Follow-up"),
                            ("surgery", "Surgery Date"),
                        ],
                        default="consultation",
                        max_length=50,
                    ),
                ),
                ("max_bookings", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["date", "start_time"],
                "unique_together": {("date", "start_time", "timezone")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Initial Consultation"),
                            ("follow_up", "Follow-up"),
                            ("pre_op", "Pre-operative Assessment"),
                            ("surgery", "Surgery"),
                            ("post_op", "Post-operative Check"),
                        ],
                        default="consultation",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "consultation_method",
                    models.CharField(
                        choices=[
                            ("video", "Video Call"),
                            ("phone", "Phone Call"),
                            ("in_person", "In Person"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Video call link (Zoom, Google Meet, etc.)",
                    ),
                ),
                (
                    "patient_notes",
                    models.TextField(
                        blank=True, help_text="Patient's questions or concerns"
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(blank=True, help_text="Doctor's internal notes"),
                ),
                (
                    "ics_file",
                    models.FileField(
                        blank=True,
                        help_text="ICS calendar file for download",
                        null=True,
                        upload_to="appointments/ics/",
                    ),
                ),
                ("reminder_sent_24h", models.BooleanField(default=False)),
                ("reminder_sent_1h", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="booking.patient",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="booking.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["time_slot__date", "time_slot__start_time"],
            },
        ),
    ]
