# Generated by Django 6.0 on 2025-12-27 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                help_text="Blood type",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_medications",
            field=models.TextField(
                blank=True,
                help_text="Current medications (duplicate for compatibility)",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Patient's profile picture",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
            ),
        ),
    ]
