# Generated by Django 6.0 on 2025-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_patient_blood_type_patient_current_medications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="consultation_method",
            field=models.CharField(
                choices=[
                    ("video", "Video Call"),
                    ("phone", "Phone Call"),
                    ("whatsapp", "WhatsApp Chat"),
                    ("in_clinic", "In-Person at Clinic"),
                ],
                default="video",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="interested_in_procedure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ilizarov", "Ilizarov (External)"),
                    ("internal", "Internal Nails"),
                    ("lon", "LON Method"),
                    ("undecided", "Not Sure Yet"),
                ],
                default="undecided",
                max_length=50,
            ),
        ),
    ]
