# Generated by Django 6.0 on 2025-12-30 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_appointment_consultation_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("patient_email", models.EmailField(max_length=254)),
                ("patient_phone", models.CharField(blank=True, max_length=20)),
                ("patient_country", models.CharField(blank=True, max_length=100)),
                ("patient_timezone", models.CharField(default="UTC", max_length=50)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("room_id", models.CharField(blank=True, max_length=100)),
                ("meeting_url", models.URLField(blank=True)),
                ("reason", models.TextField(help_text="Reason for consultation")),
                ("current_height", models.CharField(blank=True, max_length=20)),
                ("desired_height_gain", models.CharField(blank=True, max_length=20)),
                (
                    "procedure_interest",
                    models.CharField(
                        choices=[
                            ("ilizarov", "Ilizarov (External Fixator)"),
                            ("internal", "Internal Lengthening Nail"),
                            ("lon", "LON Method"),
                            ("undecided", "Not Sure Yet"),
                        ],
                        default="undecided",
                        max_length=50,
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, help_text="Relevant medical history"),
                ),
                ("doctor_notes", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("reminder_sent_24h", models.BooleanField(default=False)),
                ("reminder_sent_1h", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Consultation",
                "verbose_name_plural": "Video Consultations",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("video_consultation", "Video Consultation Fee"),
                            ("consultation_deposit", "Consultation Deposit"),
                            ("surgery_deposit", "Surgery Deposit"),
                            ("full_payment", "Full Payment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stripe_session_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="booking.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="booking.videoconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
