# Generated by Django 6.0 on 2025-12-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_videoconsultation_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="Time slot for confirmed appointments. Null for initial consultation requests.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="booking.timeslot",
            ),
        ),
    ]
