# Generated by Django 6.0 on 2026-01-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_alter_appointment_time_slot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="consultation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Consultation fee in USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Payment must be completed before this time",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easypaisa", "EasyPaisa"),
                    ("jazzcash", "JazzCash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("stripe", "Stripe (Card)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_notes",
            field=models.TextField(
                blank=True, help_text="Notes about payment verification"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot of payment (for EasyPaisa/JazzCash/Bank)",
                null=True,
                upload_to="payment_proofs/",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("submitted", "Payment Submitted"),
                    ("verified", "Payment Verified"),
                    ("failed", "Payment Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True, help_text="Stripe Payment Intent ID", max_length=255
            ),
        ),
    ]
