# Generated by Django 6.0 on 2026-01-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_add_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="full_name",
            field=models.CharField(
                blank=True, help_text="Patient's full name", max_length=200
            ),
        ),
    ]
